### ISSUE TITLE
Error importing OVF with vSphere 5 api

### ISSUE THREAD

**Issue by calavera** [rlane/rbvmomi#21]
Hi,

the latest version of the OvfManager requires a new entity to be added to the `OvfCreateImportSpecParams`, this new entity its called `instantiationOst`, check the [sdk documentation](http://pubs.vmware.com/vsphere-50/topic/com.vmware.wssdk.apiref.doc_50/vim.OvfManager.CreateImportSpecParams.html#field_detail). 

I'm not sure about how to use/add this new entity and I'm not sure either if it's actually mandatory, but without it the call to `CreateImportSpec` fails, this is the error message:

```
--> (vim.OvfManager.CreateImportSpecParams) {
-->    dynamicType = <unset>,
-->    locale = "US",
-->    deploymentOption = "",
-->    entityName = "GitHub Enterprise(11.10.257-i386) 25e06b40-7ace-012f-acab-1040f3912bd4",
-->    hostSystem = 'vim.HostSystem:ha-host',
-->    ipAllocationPolicy = <unset>,
-->    ipProtocol = <unset>,
-->    diskProvisioning = "thick",
-->    instantiationOst = (vim.OvfConsumer.OstNode) null,
--> }
```

```
2012-05-07T17:42:52.799Z [3C881B90 info 'Vmomi'] Result:
--> (vmodl.fault.ManagedObjectNotFound) {
-->    dynamicType = <unset>,
-->    faultCause = (vmodl.MethodFault) null,
-->    obj = 'vim.OvfManager:OvfManager',
-->    msg = "",
--> }
```

You can see how the `instantiationOst` is `null`.

I'd be really glad if you could take it a look and let me know how to solve this issue.

**Comment by calavera** [comment]
Btw, this is pretty much the script I'm using and the error log that I get in my code, although it's pretty much useless:

``` ruby
options = {:uri => ovf_uri, :vmName => vm_name, :diskProvisioning => :thick}
connection_options = {:host => host, :user => user, :password => passwd, :insecure => true}
vim = RbVmomi::VIM.connect connection_options

datacenter = vim.serviceInstance.find_datacenter
host_folder = datacenter.hostFolder.children.first

options[:host] = host_folder.host.first
options[:vmFolder] = datacenter.vmFolder.children.first
options[:resourcePool] = host_folder.resourcePool
options[:datastore] = options[:host].datastore.first

ovf_manager = RbVmomi::VIM::OvfManager(vim, 'OvfManager')
ovf_manager.deployOVF options
```

```
ManagedObjectNotFound: The object has already been deleted or has not been completely created
/Users/david/dev/rbvmomi/lib/rbvmomi/connection.rb:61:in `parse_response'
/Users/david/dev/rbvmomi/lib/rbvmomi/connection.rb:90:in `call'
/Users/david/dev/rbvmomi/lib/rbvmomi/basic_types.rb:203:in `_call'
/Users/david/dev/rbvmomi/lib/rbvmomi/basic_types.rb:74:in `CreateImportSpec'
/Users/david/dev/rbvmomi/lib/rbvmomi/vim/OvfManager.rb:48:in `deployOVF'
/Users/david/dev/github/enterprise/rakelib/ova.rake
```

**Comment by scottjg** [comment]
try this instead, and tell me how it goes:

``` ruby
options = {:uri => ovf_uri, :vmName => vm_name, :diskProvisioning => :thick}
connection_options = {:host => host, :user => user, :password => passwd, :insecure => true}
vim = RbVmomi::VIM.connect connection_options

datacenter = vim.serviceInstance.find_datacenter
host_folder = datacenter.hostFolder.children.first

options[:host] = host_folder.host.first
options[:vmFolder] = datacenter.vmFolder.children.first
options[:resourcePool] = host_folder.resourcePool
options[:datastore] = options[:host].datastore.first

vim.serviceContent.ovfManager.deployOVF options
```

**Comment by scottjg** [comment]
also, if that doesn't work, it would be great if i could get a look at your vpxd log file

**Comment by calavera** [comment]
@scottjg that made the trick, but it still needs the `OvfConsumerOstNode` entity. Now I get more information about the problem:

```
rake aborted!
InvalidRequest: 
Required property id is missing from data object of type OvfConsumerOstNode
Required property type is missing from data object of type OvfConsumerOstNode

while parsing serialized DataObject of type vim.OvfConsumer.OstNode
at line 94, column 478

while parsing property "instantiationOst" of static type OvfConsumerOstNode

while parsing serialized DataObject of type vim.OvfManager.CreateImportSpecParams
at line 94, column 192

while parsing call information for method CreateImportSpec
at line 1, column 177

while parsing SOAP body
at line 1, column 167

while parsing SOAP envelope
at line 1, column 0

while parsing HTTP request for method createImportSpec
on object of type vim.OvfManager
at line 1, column 0
/Users/david/dev/rbvmomi/lib/rbvmomi/connection.rb:61:in `parse_response'
/Users/david/dev/rbvmomi/lib/rbvmomi/connection.rb:90:in `call'
/Users/david/dev/rbvmomi/lib/rbvmomi/basic_types.rb:203:in `_call'
/Users/david/dev/rbvmomi/lib/rbvmomi/basic_types.rb:74:in `CreateImportSpec'
/Users/david/dev/rbvmomi/lib/rbvmomi/vim/OvfManager.rb:49:in `deployOVF'
/Users/david/dev/github/enterprise/rakelib/ova.rake:67
```

I tried adding the line below to the options but the error message it's the same:

```
options[:instantiationOst] = RbVmomi::VIM::OvfConsumerOstNode(:id => '', :type => :envelope)
```

**Comment by calavera** [comment]
Oh, I see the problem. RbVmomi::VIM::OvfManager is not using the instatiationOst from the options that I send. It needs to be added to the OvfCreateImportSpecParams, like this:

``` ruby
ovfImportSpec = RbVmomi::VIM::OvfCreateImportSpecParams(
  :hostSystem => opts[:host],
  :locale => "US",
  :entityName => opts[:vmName],
  :deploymentOption => "",
  :networkMapping => opts[:networkMappings].map{|from, to| RbVmomi::VIM::OvfNetworkMapping(:name => from, :network => to)},
  :propertyMapping => opts[:propertyMappings].to_a,
  :diskProvisioning => opts[:diskProvisioning],
  :instantiationOst => RbVmomi::VIM::OvfConsumerOstNode(:id => '', :type => :envelope)
)
```

But I guess that will fail for other vSphere previous versions.

**Comment by scottjg** [comment]
what's confusing to me is that :instantiationOst is not a required param, and i don't see our internal scripts at vmware using it. 

are you deploying through vCenter Server or directly to an esx host?

**Comment by scottjg** [comment]
i just tried bringing up an esx 5.0 host, and deploying an ovf. i used this script and it worked without error:

``` ruby
#!/usr/bin/env ruby
require 'rbvmomi'
require 'open-uri'

options = {:uri => 'http://build-squid.eng.vmware.com/build/mts/release/bora-710900/publish/exports/ovf/VMware-vCenter-Server-Appliance-5.1.0.5100-710900_OVF10.ovf', :vmName => 'test', :diskProvisioning => :thick}
connection_options = {:host => 'scottjg-esx2', :user => 'root', :password => '', :insecure => true}
vim = RbVmomi::VIM.connect connection_options

datacenter = vim.serviceInstance.find_datacenter
host_folder = datacenter.hostFolder.children.first

options[:host] = host_folder.host.first
options[:vmFolder] = datacenter.vmFolder
options[:resourcePool] = host_folder.resourcePool
options[:datastore] = options[:host].datastore.first

vim.serviceContent.ovfManager.deployOVF options
```

hmm...

**Comment by scottjg** [comment]
assuming you're also deploying to a 5.0 host, the only other variable i can think of is the actual ovf in question? just to compare, if you run with vim.debug = true (after connecting). you can look at the soap generated as a sanity check.

here's the CreateImportSpec request that I got when I ran the script:

``` xml
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <env:Body>
    <CreateImportSpec xmlns="urn:vim25">
      <_this type="OvfManager">ha-ovf-manager</_this>
      <ovfDescriptor> (..snip, contents of ovf was here) </ovfDescriptor>
      <resourcePool type="ResourcePool">ha-root-pool</resourcePool>
      <datastore type="Datastore">4bc6f83b-45317a58-1f6d-78e7d15f8d59</datastore>
      <cisp xsi:type="OvfCreateImportSpecParams">
        <locale>US</locale>
        <deploymentOption></deploymentOption>
        <entityName>test</entityName>
        <hostSystem type="HostSystem">ha-host</hostSystem>
        <diskProvisioning>thick</diskProvisioning>
      </cisp>
    </CreateImportSpec>
  </env:Body>
</env:Envelope>

```

**Comment by calavera** [comment]
Thank you Scott. I think it's solved now, but I cannot spend more time in this until next week. We're changing the way we deploy our vms and we'll probably end stopping using the ovf.
