### ISSUE TITLE
undefined method `stringify_keys' for #<RbVmomi::VIM:0x000000049c3278> 

### ISSUE THREAD

**Issue by nedoshel** [rlane/rbvmomi#26]
sometime in same code i get this and sometime not)
controller:

vms = dc.vmFolder.childEntity[0].children

or

datastore.vm.each do |vm|

like this.
what can it be?

**Comment by jcustenborder** [comment]
You mention controller. Are you using this in rails? I'm having a similar issue. It looks like active record has been injected into the call stack. Did you find a fix for your issues?

```
undefined method `stringify_keys' for #<RbVmomi::VIM:0x007feda7674020>
```

```
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/attribute_assignment.rb:69:in `assign_attributes'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/base.rb:498:in `initialize'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/deserialization.rb:185:in `new'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/deserialization.rb:185:in `deserialize'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/connection.rb:68:in `block in parse_response'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/connection.rb:68:in `map'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/connection.rb:68:in `parse_response'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/connection.rb:90:in `call'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/basic_types.rb:203:in `_call'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/vim/Folder.rb:7:in `find'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/vim/Folder.rb:83:in `traverse'
/Users/jeremy/.rvm/gems/ruby-1.9.3-p286/gems/rbvmomi-1.6.0/lib/rbvmomi/vim/ServiceInstance.rb:8:in `find_datacenter'
```

**Comment by endzyme** [comment]
If you're using rails look at  http://fog.io

**Comment by jcustenborder** [comment]
Doesn't fog use this library under the hood?

**Comment by endzyme** [comment]
Yes but it makes it much easier to work with depending on what you're doing

**Comment by rlane** [comment]
FYI, vmware/rbvmomi is the official repo now - I don't work for VMware anymore. I have no idea how ActiveRecord got itself called here.
