### ISSUE TITLE
Unable to determine type of Any when trying to remove ClusterDasVmConfigInfo

### ISSUE THREAD

**Issue by jillhubahib** [rlane/rbvmomi#34]
Hi,

We have encountered an issue while attempting to remove a VM from the VM Overrides list. This is how we did it:

```
vm_restart_priority['vm'].each do |vm|
            if remove
              unless configured_vms.include?(vm)
                logger.warn "#{vm} is currently not part of VM restart priority, so it cannot be removed"
                return false
              end
              key = get_key(mob.configuration.dasVmConfig, 'key', @client.get_vm(vm))
              das_vm_config_info << VIM.ClusterDasVmConfigSpec(
                :operation => 'remove',
                :removeKey => key
              )
            else
              operation = configured_vms.include?(vm) ? 'edit' : 'add'
              das_vm_config_info << {
                info: VIM.ClusterDasVmConfigInfo(
                  key: @client.get_vm(vm),
                  dasSettings: VIM.ClusterDasVmSettings(restartPriority: priority),
                  restartPriority: priority
                ),
                operation: operation
              }
            end
          end
        end

        spec = VIM.ClusterConfigSpecEx(dasVmConfigSpec: das_vm_config_info)
        pp spec
        begin
          task = mob.ReconfigureComputeResource_Task(spec: spec, modify: true)
          task.wait_for_completion
        rescue => e
          logger.error 'Setting of virtual machine restart priority failed!'
          logger.error e.message
          logger.error e.backtrace
          logger.error 'exiting'
          exit 1
        else
          logger.info "Virtual machine restart priority set in cluster #{mob.name}"
        end
```

This is how our spec looks like:

```
ClusterConfigSpecEx(
  dasVmConfigSpec: [ClusterDasVmConfigSpec(
     operation: "remove",
     removeKey: VirtualMachine("vm-67")
   )]
)
```

This is the error message:

```
[2014-12-08 13:24:54 #14628] ERROR -- : InvalidRequest: 
Unable to determine type of Any

error parsing Any value
at line 1, column 400

while parsing property "removeKey" of static type anyType

while parsing serialized DataObject of type vim.cluster.DasVmConfigSpec
at line 1, column 320

while parsing property "dasVmConfigSpec" of static type ArrayOfClusterDasVmConfigSpec

while parsing serialized DataObject of type vim.cluster.ConfigSpecEx
at line 1, column 283

while parsing call information for method ReconfigureComputeResource_Task
at line 1, column 177

while parsing SOAP body
at line 1, column 167

while parsing SOAP envelope
at line 1, column 0

while parsing HTTP request for method reconfigureEx
on object of type vim.ComputeResource
at line 1, column 0
[2014-12-08 13:24:54 #14628] ERROR -- : ["/var/lib/gems/1.9.1/gems/rbvmomi-1.8.1/lib/rbvmomi/connection.rb:61:in `parse_response'", "/var/lib/gems/1.9.1/gems/rbvmomi-1.8.1/lib/rbvmomi/connection.rb:90:in `call'", "/var/lib/gems/1.9.1/gems/rbvmomi-1.8.1/lib/rbvmomi/basic_types.rb:205:in `_call'", "/var/lib/gems/1.9.1/gems/rbvmomi-1.8.1/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'", "/home/jill/Documents/gitrepo/trunk/my_core/lib/my_core/cluster.rb:548:in `set_vm_restart_priority'", "/home/jill/Documents/gitrepo/trunk/my_cli/lib/my_cli/cluster_action.rb:215:in `remove_vm_restart_priority'", "/home/jill/Documents/gitrepo/trunk/my_cli/lib/my_cli/common_action.rb:96:in `run'", "./bin/my_cli:13:in `<main>'"]

```

Please, badly need help ...

**Comment by jillhubahib** [comment]
Same error with below spec structure:

```
ClusterConfigSpecEx(
  dasVmConfigSpec: [{:info=>
     ClusterDasVmConfigInfo( key: VirtualMachine("vm-67") ),
    :operation=>"remove",
    :removeKey=>VirtualMachine("vm-67")}]
)
```
