### ISSUE TITLE
RbVmomi::Fault: InvalidRequest: Not initialized: vim.TaskFilterSpec.TimeOption timeType

### ISSUE THREAD

**Issue by jbbarth** [rlane/rbvmomi#7]
Hi there,

First thanks for this great gem, I use it every day for 1 or 2 months and even if the vmware API is a bit complicated, the gem does a great job so far !

Today I'm trying to list all the tasks that happened in the last day or so. Here's the script :

``` ruby
%w(trollop rbvmomi rbvmomi/trollop json).each{|f| require f}
VIM = RbVmomi::VIM
vim = VIM.connect(:host=>"XXXXXXX",:port=>443,:insecure=>true,:user=>"xxxxxxx",:password=>"xxxxxxx")
filter = VIM::TaskFilterSpec.new(:time => VIM::TaskFilterSpecByTime.new(:beginTime => DateTime.now - 1))
tm = vim.serviceContent.taskManager.CreateCollectorForTasks(:filter => filter)
```

But it fails with the following error message :

```
RbVmomi::Fault: InvalidRequest: Not initialized: vim.TaskFilterSpec.TimeOption timeType
        from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/connection.rb:47:in `parse_response'
        from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/connection.rb:71:in `call'
        from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/basic_types.rb:187:in `_call'
        from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/basic_types.rb:69:in `block (2 levels) in init'
        from (irb):12
        from /usr/local/rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in `<main>'
```

Any idea about this exception ? A hint to collect tasks < 24hrs ?

Thanks

**Comment by rlane** [comment]
I think you need to have a timeType field set in the TaskFilterSpecByTime. I'd write this code as:

``` ruby
vim.serviceContent.taskManager.CreateCollectorForTasks(
  filter: {
    time: { timeType: :queued, beginTime: DateTime.now - 1 }
  }
)
```

RbVmomi can figure out the type information most of the time so you don't need to write it out. If you do want to use the full type name you can drop the ".new" at the end.

While this code should work the server threw an InvalidArgument fault when I tried it, so YMMV.

**Comment by jbbarth** [comment]
Same here, but I confirm your tip solves the initial exception :

```
>> vim.serviceContent.taskManager.CreateCollectorForTasks(filter: { time: { beginTime: DateTime.now - 1 } })
RbVmomi::Fault: InvalidRequest: Not initialized: vim.TaskFilterSpec.TimeOption timeType
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/connection.rb:47:in `parse_response'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/connection.rb:71:in `call'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/basic_types.rb:187:in `_call'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/basic_types.rb:69:in `block (2 levels) in init'
    from (irb):19
    from /usr/local/rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in `<main>'
>> vim.serviceContent.taskManager.CreateCollectorForTasks(filter: { time: { timeType: :queued, beginTime: DateTime.now - 1 } })
RbVmomi::Fault: InvalidRequest: Invalid argument
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/connection.rb:47:in `parse_response'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/connection.rb:71:in `call'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/basic_types.rb:187:in `_call'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@vmware/gems/rbvmomi-1.4.0/lib/rbvmomi/basic_types.rb:69:in `block (2 levels) in init'
    from (irb):20
    from /usr/local/rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in `<main>'
```

You can keep the ticket closed, thanks for the help !

**Comment by jbbarth** [comment]
Oh, in fact the new exception is raised because "timeType" should be "queuedTime", not "queued". See authorized values here : http://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.TaskFilterSpec.TimeOption.html. FYI here's the working code :

```
>> vim.serviceContent.taskManager.CreateCollectorForTasks(filter: { time: { timeType: :queuedTime, beginTime: (DateTime.now - 1) } })=> TaskHistoryCollector("session[F6C8B7FC-7D4C-4726-B69A-E4E4C8A72FFE]D5AD0FE8-BAE1-477C-9EAE-97840C6A4AED")
```

Thanks again !
